'use client'

/**
 * Small, gentle sounds for key moments, the same set as the iPhone app (generated by
 * ios/design/sounds.py into web/public/sounds). Never before the first tap or key press,
 * never when the person turned them off, and never louder than a soft chime.
 */
export type SoundName =
  | 'tap'
  | 'select'
  | 'send'
  | 'success'
  | 'start'
  | 'finish'
  | 'levelup'
  | 'breathe-in'
  | 'breathe-out'
  | 'error'

const KEY = 'rondje.sounds'
const EVENT = 'rondje:sounds'

let unlocked = false
const cache = new Map<SoundName, HTMLAudioElement>()

if (typeof window !== 'undefined') {
  const unlock = () => {
    unlocked = true
    window.removeEventListener('pointerdown', unlock)
    window.removeEventListener('keydown', unlock)
  }
  window.addEventListener('pointerdown', unlock, { passive: true })
  window.addEventListener('keydown', unlock)
}

export function soundsEnabled(): boolean {
  try {
    return localStorage.getItem(KEY) !== '0'
  } catch {
    return false
  }
}

export function setSoundsEnabled(on: boolean) {
  try {
    localStorage.setItem(KEY, on ? '1' : '0')
  } catch {}
  window.dispatchEvent(new Event(EVENT))
  if (on) playSound('select')
}

/** For useSyncExternalStore: re-render when the setting changes (also in another tab). */
export function subscribeSounds(onChange: () => void) {
  window.addEventListener(EVENT, onChange)
  window.addEventListener('storage', onChange)
  return () => {
    window.removeEventListener(EVENT, onChange)
    window.removeEventListener('storage', onChange)
  }
}

export function playSound(name: SoundName, volume = 0.5) {
  if (typeof window === 'undefined' || !unlocked || !soundsEnabled()) return
  try {
    let audio = cache.get(name)
    if (!audio) {
      audio = new Audio(`/sounds/${name}.wav`)
      audio.preload = 'auto'
      cache.set(name, audio)
    }
    const shot = audio.cloneNode(true) as HTMLAudioElement
    shot.volume = Math.min(1, Math.max(0, volume))
    void shot.play().catch(() => {})
  } catch {}
}
